services:
  kong:
    image: kong:3.4
    container_name: test-kong
    restart: always

    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /opt/kong_gateway/kong.yml
      

      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000

    volumes:
      - ./kong.yml:/opt/kong_gateway/kong.yml

    ports:
      - "8000:8000"
      - "8001:8001" 